Workspace: /tmp/vscode_pydev_ws_226b0/pydev_ws
Arguments: -Declipse.application=org.python.pydev.pydev_lsp.application,-Dosgi.bundles.defaultStartLevel=4,-Declipse.product=org.python.pydev.pydev_lsp.product,-jar,/home/divum/.vscode/extensions/fabioz.vscode-pydev-0.1.5/server/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar,-configuration,/home/divum/.vscode/extensions/fabioz.vscode-pydev-0.1.5/server/config_linux,-data,/tmp/vscode_pydev_ws_226b0/pydev_ws
[Error - 12:21:45 PM] 20 Feb, 2019 12:21:41 PM Info: Rebuilding internal caches: /tmp/vscode_pydev_ws_226b0/pydev_ws/.metadata/.plugins/com.python.pydev.analysis/python_v1_bm109oo8jsa5gnqmc06ekl12p/python.pydevsysteminfo (Expected error to be provided and got no error!)
[Error - 12:21:52 PM] 20 Feb, 2019 12:21:41 PM Error creating link to: /tmp/vscode_pydev_ws_226b0/pydev_ws in location: F/pydev-ls-project/pydev_ws - /tmp/vscode_pydev_ws_226b0/pydev_ws/pydev-ls-project/pydev_ws
Error creating link to: /tmp/vscode_pydev_ws_226b0/pydev_ws in location: F/pydev-ls-project/pydev_ws - /tmp/vscode_pydev_ws_226b0/pydev_ws/pydev-ls-project/pydev_ws
java.lang.RuntimeException: Error creating link to: /tmp/vscode_pydev_ws_226b0/pydev_ws in location: F/pydev-ls-project/pydev_ws - /tmp/vscode_pydev_ws_226b0/pydev_ws/pydev-ls-project/pydev_ws
	at org.python.pydev.pydev_lsp.PyDevProjects.createFolderLinkTo(PyDevProjects.java:203)
	at org.python.pydev.pydev_lsp.PyDevProjects.updateProjectPythonPath(PyDevProjects.java:168)
	at org.python.pydev.pydev_lsp.PyDevWorkspaceService.didChangeConfiguration(PyDevWorkspaceService.java:233)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:51)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:126)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:165)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:136)
	at org.eclipse.ls.core.ParentProcessWatcher.lambda$0(ParentProcessWatcher.java:70)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:149)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:77)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:84)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.eclipse.core.internal.resources.ResourceException: '/tmp/vscode_pydev_ws_226b0/pydev_ws' is not a valid location for linked resources.
	at org.eclipse.core.internal.resources.Resource.assertLinkRequirements(Resource.java:175)
	at org.eclipse.core.internal.resources.Resource.createLink(Resource.java:640)
	at org.eclipse.core.internal.resources.Resource.createLink(Resource.java:616)
	at org.python.pydev.pydev_lsp.PyDevProjects.createFolderLinkTo(PyDevProjects.java:200)
	... 19 more

[Error - 12:21:52 PM] 20 Feb, 2019 12:21:41 PM Info: Rebuilding internal caches: /tmp/vscode_pydev_ws_226b0/pydev_ws/.metadata/.plugins/org.eclipse.core.resources/.projects/pydev-ls-project/com.python.pydev.analysis/AdditionalProjectInterpreterInfo.pydevinfo (Expected error to be provided and got no error!)
